### ISSUE TITLE
Add a margin between stacked boxes for mobile view (they overlap)

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/RateMyPDF#21]
I noticed when you change the viewport size, the landing page's information boxes can overlap. They shouldn't do that.

**Comment by KindBill** [comment]
![image](https://github.com/SuffolkLITLab/RateMyPDF/assets/61289898/2b7fbde4-cc8e-409c-9b11-b4f4049b1596)

**Comment by codestronger** [comment]
Adjusted the margins and positioning for the checkmark image on smaller devices. Screenshots to follow. Let me know if that looks okay now.


**Upload Page (Before changes)**

Mobile:
<img width="621" alt="ratemypdf-upload-before-samsung-galaxy-s8" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/968a3772-379e-4507-8e46-aaf358c047f5">
<img width="593" alt="ratemypdf-upload-before-iphone-12-pro" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/8671ba53-3f67-4537-bd47-1a29ef034c70">

Desktop:
<img width="828" alt="ratemypdf-upload-before-desktop" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/26b0798f-ffff-4166-bea5-3d8fdf0c44eb">


**Upload Page (After changes)**

Mobile:
<img width="607" alt="ratemypdf-upload-after-samsung-galaxy-s8" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/2e6e9492-e721-4026-afeb-595d19b359fe">
<img width="554" alt="ratemypdf-upload-after-iphone-12-pro" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/bdf3248b-9b80-485d-af6e-a215e5c73b37">

Desktop:
<img width="876" alt="ratemypdf-upload-after-desktop" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/3be564e9-67d4-465a-816b-87fff4d288a5">


**Stats Page (Before Changes)**

Mobile:
<img width="596" alt="ratemypdf-stats-before-samsung-galaxy-s8" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/a4c795c5-d3db-4229-b5dc-37f8d39bdfa7">
<img width="565" alt="ratemypdf-stats-before-iphone-12-pro" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/166e9622-ed67-4f3b-92c6-bf8cd6bb5f8f">

Desktop:
<img width="880" alt="ratemypdf-stats-before-desktop" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/ede3aa93-8e4c-4178-ab04-b2e05a36aae0">


**Stats Page (After Changes)**

Mobile:
<img width="639" alt="ratemypdf-stats-after-samsung-galaxy-s8" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/d0fd1261-34f6-4864-83ac-daaaea969bf7">
<img width="586" alt="ratemypdf-stats-after-iphone-12-pro" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/87089d78-8d47-4d81-a600-2a4b76852b42">

Desktop:
<img width="887" alt="ratemypdf-stats-after-desktop" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/db3f98ec-64c9-4d90-9a4b-b360759c7f6c">
