### ISSUE TITLE
Make the summary page printable

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/RateMyPDF#29]
Testers so liked they tool's output that they wanted to come back to it or have it available for reference on paper. They also saw it as a valuable tool to help advocate for improving existing forms (e.g., look at how many hard to understand phrases we have). To this end it might make sense to repackage the tools output into a docx such that users could easily include it in reports et al. In the very least there should be a way to print or save the output. As it stands, the accordion menus made this difficult.

**Comment by nonprofittechy** [comment]
Instead of adding in a DOCX as output, I suggest we add a CSS layer that makes the content more nicely laid out for printing to PDF. It could also be a button.

**Comment by KindBill** [comment]
After review with Quinten, expand all collapsed elements so that it's printable when printed.

Include everything; detailed statistics can be stacked.

**Comment by codestronger** [comment]
Question that's related to making the page printable but also spills into the accordion design of the web version: Is the behavior of the last accordion item intended to be different from the rest?

The last accordion item, "What we can't detect yet," is unique in that it can be expanded/collapsed independently of the other accordion items. It also has a different background color when expanded so it blends into the parent container. The top 4 accordion items are mutually exclusive, so at most 1 can be expanded at a time.

In the print version, I can expand everything as-is. Or we can make the background match the other accordions, either just in the print version or for both web & print. We could also standardize all the accordion items to either be independently expandable or mutually exclusive.

**Comment by codestronger** [comment]
Some screenshots for context:


Accordion Item Expanded:
<img width="766" alt="ratemypdf-reduce-the-number-of-words-per-page-expanded" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/5a44d9ba-7d4f-442f-b3b4-1c79a367f6ad">

What We Can't Detect Yet Expanded:
<img width="843" alt="ratemypdf-what-we-cant-detect-expanded" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/dfb64878-5ae8-4af7-9822-ef1a5bc9ee31">

Both Types of Accordion Items Expanded at the same time:
<img width="750" alt="ratemypdf-what-we-cant-detect-with-other-accordion-expanded" src="https://github.com/SuffolkLITLab/RateMyPDF/assets/19370549/0d96351a-88bc-478c-b898-a48b8475e080">

**Comment by nonprofittechy** [comment]
Not intentional, just an accident. Let's make them all behave the same

**Comment by codestronger** [comment]
Sounds good! I standardized the accordion behavior. Also made adjustments to the headline background so the print version of that looks nicer and fixed the display of the stat charts.

Attached below are reference copies of the before/after in Chrome & Firefox:

**After**
[ratemypdf-ff-print-after5.pdf](https://github.com/user-attachments/files/15506438/ratemypdf-ff-print-after5.pdf)
[ratemypdf-chrome-print-after5.pdf](https://github.com/user-attachments/files/15506439/ratemypdf-chrome-print-after5.pdf)

**Before**
[ratemypdf-ff-print-before.pdf](https://github.com/user-attachments/files/15506440/ratemypdf-ff-print-before.pdf)
[ratemypdf-chrome-print-before.pdf](https://github.com/user-attachments/files/15506441/ratemypdf-chrome-print-before.pdf)
